class NotFoundError(Exception):
    pass


class NotUniqueError(Exception):
    pass
